name: Deploy Marketing Site to S3

on:
  push:
    branches: [ main ]
    paths:
      - 'Marketing/**'
      - '.github/workflows/deploy-marketing-site.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
    paths:
      - 'Marketing/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_BUCKET: better-call-saul-marketing
  CLOUDFRONT_DISTRIBUTION_ID: ESFK92TFOJSWA

jobs:
  deploy_marketing_site:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Deploy Marketing Site
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync Marketing/ s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          if [ -n "${{ env.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          else
            echo "CloudFront distribution ID not set - skipping cache invalidation"
          fi